#!/bin/sh
# Change Conservation Mode - Only accepts certain inputs
CONSERVATION_FILE="/sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/conservation_mode"

# For testing on machines without a conservation_mode file
if [ $CONSERVATION_TEST_ENV = 1 ]
then
    CONSERVATION_FILE="/tmp/conservation_mode"
fi

if [ "$1" = "file" ]
then
    echo $CONSERVATION_FILE;
elif [ "$1" = "status" ]
then
    cat $CONSERVATION_FILE
elif [ "$1" = "on" ]
then 
    echo 1| sudo tee $CONSERVATION_FILE
elif [ "$1" = "off" ]
then 
    echo 0| sudo tee $CONSERVATION_FILE
elif [ "$1" = "help" ] || [ "$1" = "--help" ]
then
    printf " help/--help : help \n on/off : turns conservation_mode on/off \n status : returns on/off (1/0)\n"
fi
